---
title: Gerrymandering Metrics
format: typst
---

```{r}
precinct <- read_csv("data/state_g24_sov_data_by_g24_srprec.csv")
g24_precinct_clean <- precinct |>
  select(district = CDDIST,dem1 = CNGDEM01,dem2 = CNGDEM02,rep1 = CNGREP01,rep2 = CNGREP02) |>
  mutate(district = as.integer(district),dem1 = na_if(dem1, "***"),dem2 = na_if(dem2, "***"),rep1 = na_if(rep1, "***"),rep2 = na_if(rep2, "***"),dem1 = as.numeric(dem1),dem2 = as.numeric(dem2),rep1 = as.numeric(rep1),rep2 = as.numeric(rep2),dem_votes = dem1 + dem2,rep_votes = rep1 + rep2,total_votes = dem_votes + rep_votes) |>
  filter(total_votes > 0)
g24_district <- g24_precinct_clean |>
  group_by(district) |>
  summarise(dem = sum(dem_votes),rep = sum(rep_votes)) |>
  mutate(total = dem + rep,rep_share = rep / total)
mean_median <- mean(g24_district$rep_share) - median(g24_district$rep_share)
mean_median

wasted_votes <- function(vA, vB) {
  total <- vA + vB
  threshold <- floor(total / 2) + 1
  winA <- vA > vB
  WA <- ifelse(winA, vA - threshold, vA)
  WB <- ifelse(winA, vB, vB - threshold)
  list(WA = WA, WB = WB)
}
wv <- wasted_votes(g24_district$rep, g24_district$dem)
EG <- (sum(wv$WB) - sum(wv$WA)) / sum(g24_district$total)
EG


```

```{r}
final_results <- final_results |>
  mutate(rep_share = Total_Allocated_REP_Votes / Total_Votes)
mean_median_new <- mean(final_results$rep_share) - median(final_results$rep_share)
mean_median_new

wasted_votes <- function(vA, vB) {
  total <- vA + vB
  threshold <- floor(total / 2) + 1
  winA <- vA > vB
  WA <- ifelse(winA, vA - threshold, vA)
  WB <- ifelse(winA, vB, vB - threshold)
  list(WA = WA, WB = WB)
}
wv_newmap <- wasted_votes(final_results$Total_Allocated_REP_Votes,final_results$Total_Allocated_DEM_Votes)
EG_new <- (sum(wv_newmap$WB) - sum(wv_newmap$WA)) / sum(final_results$Total_Votes)
EG_new

```


### 2024 Election Results and the 2024 District Map



### 2024 Election Results and the proposed 2025 District Map

